services:
  # 1. MySQL 資料庫容器
  db:
    image: mysql:8.0
    container_name: yuntech_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_password_123  # Root 密碼
      MYSQL_DATABASE: smart_pot_db            # 專案資料庫名稱
      MYSQL_USER: group5_admin                # 管理員帳號
      MYSQL_PASSWORD: admin_password_555       # 管理員密碼
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - default
  # 2. PhpMyAdmin 網頁管理介面容器
  phpmyadmin:
    image: phpmyadmin:latest
    container_name: yuntech_phpmyadmin
    restart: always
    environment:
      PMA_HOST: db
    ports:
      - "8080:80"  # 透過 http://<Pi5_IP>:8080 登入
    depends_on:
      - db
    networks:
      - default
  # 🌐 3. Django 網頁系統容器（新增）
  web:
    build: .
    container_name: yuntech_plant_web
    restart: always
    volumes:
      - .:/code
    command: sh /code/wait-for-db.sh
    depends_on:
      - db      # 確保資料庫先啟動，Django 才能連線
      - nodered
    networks:
      - default
  # 🧱 4. Nginx 反向代理容器
  nginx:
    image: nginx:stable-alpine
    container_name: yuntech_nginx
    restart: always
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "80:80"
    depends_on:
      - web
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - default
  # 📈 5. Node-RED 數據視覺化中樞容器（新增）
  nodered:
    image: nodered/node-red:latest
    container_name: yuntech_plant_nodered
    restart: always
    networks:
      - default
    ports:
      - "1880:1880"  # 透過 http://<Pi5_IP>:1880 進入畫布 /ui 進入指針儀表板
    volumes:
      - nodered-data:/data

  my_personal_web:
    build: ../myiotweb  # 🌟 密技：用 ../ 跨出大專案資料夾，直接指向隔壁的個人網站 Repo
    container_name: yuntech_member1_personal
    restart: always
    depends_on:
      - db
    volumes:
      - ../myiotweb:/app
    networks:
      - default  # 加入同一個網路，確保容器間通訊無礙

  yuntech_member2_personal:  
    build:
      context: /home/liaofengjun/web
      dockerfile: Dockerfile
    restart: always
    environment:
      - DEBUG=1
      - Mariadb_tls_disabled_peer_verification=1
      - MYSQL_client_ssl_mode=DISABLED
    ports:
      - "8001:8001"
    depends_on:
      - db
    volumes:
     - /home/liaofengjun/web:/app
    # 🌟 祺翔，關鍵是加上下面這兩行！讓他加入你們的大專案網路
    networks:
      - default  # ⚠️ 請確認這個名字跟你們 yml 最底部定義的 network 名字一模一樣（例如 yuntech_network 或是 teamweb_network）
    command: python manage.py runserver 0.0.0.0:8001

volumes:
  mysql_data:
  nodered-data:  # 確保 Node-RED 拉好的 4 路半圓圖表在重啟後不會消失
networks:
  default:
    name: yuntech_network  # 統一命名網路，讓容器間通訊更順暢