server {
    listen 80;
    server_name localhost;

    # 🌟 1. 你 (組員 A) 的個人網站 (用 8002)
    location /member1/ {
        proxy_pass http://my_personal_web:8002/; 
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    # 🌟 2. 組員 B 的個人網站 (本機跑 8001)
    location /member2/ {
        proxy_pass http://teamweb-yuntech_member2_personal-1:8001/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    # 🌟 3. 組員 C 的個人網站 (本機跑 8008)
    location /member3/ {
    # 透過 Docker 的特殊域名連回宿主機的 8008 端口
    proxy_pass http://host.docker.internal:8008/;
    
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
}

    # 🌟 4. 核心大專題網站 (Django 容器) - 移到最下面墊底！
    location / {
        proxy_pass http://web:8000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }


    # 讓 Nginx 統一控管 Node-RED，這樣 ngrok 才能一魚多吃
    location /nodered/ {
        proxy_pass http://yuntech_plant_nodered:1880/; 
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        # 如果有用到 WebSocket（控制拉桿、即時圖表），要加下面這兩行
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
    }
}